CREATE TABLE plans (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 code VARCHAR(50) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 monthly_price_cents INT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
